image: conanio/clang8

stages: 
    - build 
    - test
    
job 1: 
    stage: build 
    before_script:
        - apt-get update && apt-get install -y make autoconf
    script: make

job 2: 
    stage: test
    before_script:
        - apt-get update && apt-get install -y make autoconf
    script: make testsuite && bin/run-tests
