# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: conanio/clang8

stages: 
    - build 
    - test
    
job 1: 
    stage: build 
    script: mkdir bin && clang++ src/main.cc $(find src -type f -name *.cc ! -name main.cc) -o bin/potato-sat

job 2: 
    stage: test
    script: mkdir bin && clang++ test/test.cc $(find src -type f -name *.cc ! -name main.cc) -o bin/run-tests && bin/run-tests
