# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: conanio/clang8

stages: 
    - build 
    - test
    
job 1: 
    stage: build 
    before_script:
        - apt-get update && apt-get install -y make autoconf
    script: make

job 2: 
    stage: test
    script: make testsuite && bin/run-tests
